### PR TITLE
Added basic message ui.

### PR DESCRIPTION
**Pull request by LawrenceHan**
Changed from protobuf objc to standard protobuf.
Regenerated protobuf files.
Changed run script from every time to only when install.

### CODE REVIEW

**Comment by LawrenceHan** [comment]
- [ ] Fork the repo and create your branch from master.
- [ ] Update code or documentation if you have changed APIs.
- [ ] Add the copyright notice to the top of any new files you've added.
- [ ] Check your code lints and checkstyles.
- [ ] Test and test again your code.
- [ ] Now, you can submit your pull request on dev or hotfix branch.
@garryyan

**Comment by garryyan** [comment]
run script from every time to only when install.    这个第一次用的时候会编译失败的。

**Comment by LawrenceHan** [comment]
这。。。那我改回去吧

**Comment by LawrenceHan** [comment]
@garryyan 您再看看/试试？

**Comment by shockcao** [comment]
@LawrenceHan 请问下你改用了什么objc protobuffer
和之前我们使用的github上开源的有什么区别呢？

**Comment by LawrenceHan** [comment]
本质上是没区别的。但是使用上有点小区别。考虑到这是一个开源的项目，出于通用性的考虑，我觉得还是换成standard proto file比较好一点。新生成的文件是基于原有的proto file生成的。

比如之前是这样生成对象

`[[[[HelloRequest builder] setUser:@"caoshaokun"] setText:@"Hello world!"] build];`

Google官方成生的只要new一下就好了。官方文档的说明是`不跨线程的话，和某通的nsobject对象一样，跨线程的话，只要不改变里面的值，也是一样`

>
The objects generated for messages should work like any other Objective C object. They are mutable objects, but if you don't change them, they are safe to share between threads (similar to passing an NSMutableDictionary between threads/queues; as long as no one mutates it, things are fine).

[Reference](https://github.com/google/protobuf/tree/master/objectivec)

**Pull request merged**
