### PR TITLE
Non-interactively mars native build failure under the Mac env. #156

### PR DESCRIPTION
**Pull request by easyfan**
https://github.com/Tencent/mars/issues/156
Add a variable:
`WITH_SCRIPT`
For indicating that whether need replace NDK_BUILD_CMD patterns. While the NDK_BUILD_CMD is generated in non-interactive mode, no further replacement works needed.

### CODE REVIEW

**Comment by garryyan** [comment]
is it better to use variable "flag"  rather than "WITH_SCRIPT"?

**Comment by easyfan** [comment]
Good point. But personally I'd like to replace the local variable 'flag' by global "WITH_SCRIPT", as the naming "WITH_SCRIPT" would be better in meanings. Dont you think?
I will update my changes later. 

Thanks.

**Comment by garryyan** [comment]
yes, the meaning of "flag"  is unclear. it is better to use "WITH_SCRIPT" to replace it.

**Comment by easyfan** [comment]
Commit updated.

**Pull request merged**
